name: Test2
on:
  pull_request:
    branches:
      - main
jobs:
  path-check:
    # packages/test2/**'に変更があれば、test jobに進む
    runs-on: ubuntu-latest
    steps:
      - name: Check path
        run: |
          echo "Checking path"
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "packages/test2/"; then
            echo "Path has changed"
          else
            echo "Path has not changed"
            exit 1
          fi
  test:
    runs-on: ubuntu-latest
    needs: path-check
    steps:
      - name: Run tests
        run: echo "Running test2"
      - name: Failure
        run: exit 1
