name: Test2
on:
  pull_request:
    branches:
      - main
jobs:
  path-check:
    runs-on: ubuntu-latest
    outputs:
      changes_in_test2: ${{ steps.filter.outputs.test2 }}
    steps:
      - uses: actions/checkout@v3
      - id: filter
        name: Check for changes in packages/test2
        run: |
          echo "::set-output name=test2::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'packages/test2/' && echo 'true' || echo 'false')"

  build:
    needs: path-check
    runs-on: ubuntu-latest
    if: needs.path-check.outputs.changes_in_test2 == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo "Building because changes were detected in packages/test2/"
