name: Test1
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/test1/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running test1"
      - name: Failure
        run: exit 1
